name: Sheets Generator
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout BFF
        uses: actions/checkout@v3
        with:
          repository: loft-br/b2b-insights-bff
          ref: main
        
