name: Sheets Generator
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout MLOps tools repo
        uses: actions/checkout@v3
        with:
          repo: loft-br/mlops-platform-tools
          ref: v2.2.2
        