name: Sheets Generator
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mlops tools
        run: |
          echo "/home/runner/.local/bin/" >> $GITHUB_PATH
          pip install git+ssh://git@github.com/loft-br/mlops-platform-tools.git@v2.2.2