name: Model deploy
on:
  workflow_dispatch:
  create:
    tags:
      - "*"

jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Do something
        run: echo "oi to the world"
