name: endpoint  deploy
on:
  workflow_dispatch:
  create:
    tags:
      - "*"

jobs:
  stage:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/stage_deploy.yaml    
  production:
    runs-on: ubuntu-latest
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/production_deploy.yaml


