name: Model deploy
on:
  workflow_dispatch:
  create:
    tags:
      - "*"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Greetings
        run: echo "oi to the world"
      - name: Stage deploy
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "From a workflow dispatch"
      - name: Production deploy
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        run: echo "Production deploy of tag ${{ github.ref_name }}"

