name: endpoint  deploy
on:
  workflow_dispatch:
  create:
    tags:
      - "*"

jobs:
  initialization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Stage deploy
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Stage deploy of branch ${{ github.ref_name }}"
        # - name: Production deploy
        #if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        #run: echo "Production deploy of tag ${{ github.ref_name }}"
  production:
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/production_deploy.yaml


