name: endpoint production deploy
on:
  workflow_call:

jobs:
  production_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: |
          echo "I'm deploying something on production"
          echo ${{ github.ref_name }}
